services:
  mjpeg-server:
    container_name: mjpeg-server
    restart: always
    build: .
    image: mjpeg-server:latest
    volumes:
      - ./config.example.yaml:/mjpeg-server/config.yaml
    ports:
      - "8080:8080"
 